// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/Clock.vue')['default']
    Quote: typeof import('./src/components/Quote.vue')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
    Time: typeof import('./src/components/Time.vue')['default']
  }
}
